# Generated by Django 4.1.6 on 2023-02-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_alter_account_id_alter_branch_id_alter_district_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Phone_number',
            field=models.CharField(max_length=10, verbose_name='Phone number'),
        ),
    ]
