# Generated by Django 4.1.6 on 2023-02-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_alter_userdetails_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='age',
            field=models.CharField(max_length=3, null=True, verbose_name='Age'),
        ),
    ]
